version: '3.8'

services:
  hbbs:
    container_name: rustdesk-hbbs
    ports:
      - "21115:21115"
      - "21116:21116"
      - "21116:21116/udp"
    image: rustdesk/rustdesk-server:latest
    command: hbbs -r localhost:21117
    volumes:
      - ./data:/root
    networks:
      - rustdesk-net
    depends_on:
      - hbbr
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  hbbr:
    container_name: rustdesk-hbbr
    ports:
      - "21117:21117"
      - "21119:21119"
    image: rustdesk/rustdesk-server:latest
    command: hbbr
    volumes:
      - ./data:/root
    networks:
      - rustdesk-net
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  rustdesk-net:
    driver: bridge